### ISSUE TITLE
PHP 8 - array_shift(): Argument #1 ($array) must be passed by reference, value given

### ISSUE THREAD

**Issue by acalvino4** [ExpressionEngine/ExpressionEngine#1537]
When I upgrade to PHP 8, I see this error on my webpage:
```
array_shift(): Argument #1 ($array) must be passed by reference, value given
ee/legacy/libraries/relationship_parser/VariableFinder.php, line 69
```

A stack trace reveals that this is a result of ce_cache making the following call:
```
EE_Template->parse('{!-- ra:0000000...', false, 1, false)
```

Of course I can disable debugging to hide this warning, but then I risk missing real issues.

Can someone tell me if the call from ce_cache is still considered supported?
* if so, EE needs to update their code to prevent this warning, and we would love confirmation that this is an accepted bug
* if not, we will consider ce_cache incompatible with php8 / ee6 and look for alternatives

**Comment by intoeetive** [comment]
I don't believe CE Cache is being supported for anything greater than EE3 (which does not support PHP8 in turn): https://docs.causingeffect.com/expressionengine/ce-cache/index.html

There are few caching-related add-ons listed on https://expressionengine.com/add-ons , [Speedy](https://expressionengine.com/add-ons/speedy) being most notable.

As a side note, in latest EE version like 69 in `VariableFinder.php` has this code
```
$newmatch = [];
```
so you might want to update ExpressionEngine as well

**Comment by acalvino4** [comment]
The fact that it was CE Cache that called this EE code is kinda beside the point, bc it is EE's code that is throwing the error. If ce_cache is called EE's api is a supported way in this case, then EE has an issue.

Here is the complete stack trace:
```
#0 <path>/system/ee/legacy/libraries/relationship_parser/VariableFinder.php(42): VariableFinder->findInTags('\n    {if poll_a...')
#1 <path>/system/ee/legacy/libraries/relationship_parser/Tree_builder.php(229): VariableFinder->find('\n    {if poll_a...')
#2 <path>/system/ee/legacy/libraries/relationship_parser/Tree_builder.php(80): EE_relationship_tree_builder->_build_tree('\n    {!-- ra:00...')
#3 <path>/system/ee/legacy/libraries/Relationships_parser.php(117): EE_relationship_tree_builder->build_tree(Array, '\n    {!-- ra:00...')
#4 <path>/system/ee/legacy/libraries/channel_entries_parser/components/Relationship.php(72): EE_Relationships_parser->create(Array, Array, '\n    {!-- ra:00...', Array)
#5 <path>/system/ee/legacy/libraries/channel_entries_parser/Preparser.php(104): EE_Channel_relationship_parser->pre_process('\n    {!-- ra:00...', Object(EE_Channel_preparser))
#6 <path>/system/ee/legacy/libraries/Channel_entries_parser.php(203): EE_Channel_preparser->__construct(Object(Channel), Object(EE_Channel_parser), Array, Array, Array)
#7 <path>/system/ee/legacy/libraries/Channel_entries_parser.php(169): EE_Channel_parser->pre_parser(Object(Channel), Array, Array, Array)
#8 <path>/system/ee/ExpressionEngine/Addons/channel/mod.channel.php(2449): EE_Channel_parser->parse(Object(Channel), Array, Array)
#9 <path>/system/ee/ExpressionEngine/Addons/channel/mod.channel.php(255): Channel->parse_channel_entries()
#10 <path>/system/ee/legacy/libraries/Template.php(1702): Channel->entries()
#11 <path>/system/ee/legacy/libraries/Template.php(1386): EE_Template->process_tags()
#12 <path>/system/ee/legacy/libraries/Template.php(560): EE_Template->tags()
#13 <path>/system/user/addons/ce_cache/mod.ce_cache.php(1011): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
#14 <path>/system/user/addons/ce_cache/mod.ce_cache.php(154): Ce_cache->parse_as_template('{!-- ra:0000000...')
#15 <path>/system/user/addons/ce_cache/mod.ce_cache.php(75): Ce_cache->save()
#16 <path>/system/ee/legacy/libraries/Template.php(1702): Ce_cache->it()
#17 <path>/system/ee/legacy/libraries/Template.php(1386): EE_Template->process_tags()
#18 <path>/system/ee/legacy/libraries/Template.php(560): EE_Template->tags()
#19 <path>/system/ee/legacy/libraries/Template.php(228): EE_Template->parse('{!-- ra:0000000...', true, 1, false)
#20 <path>/system/ee/legacy/libraries/Template.php(1070): EE_Template->fetch_and_parse('embeds', '.poll-widget', true, 1)
#21 <path>/system/ee/legacy/libraries/Template.php(959): EE_Template->process_sub_templates('{!-- ra:0000000...')
#22 <path>/system/ee/legacy/libraries/Template.php(601): EE_Template->process_layout_template('{!-- ra:0000000...', NULL)
#23 <path>/system/ee/legacy/libraries/Template.php(228): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
#24 <path>/system/ee/legacy/libraries/Template.php(163): EE_Template->fetch_and_parse('', Array, false)
#25 <path>/system/ee/legacy/libraries/Core.php(647): EE_Template->run_template_engine('', '')
#26 <path>/system/ee/legacy/controllers/ee.php(53): EE_Core->generate_page()
#27 [internal function]: EE->index()
#28 <path>/system/ee/ExpressionEngine/Core/Core.php(251): call_user_func_array(Array, Array)
#29 <path>/system/ee/ExpressionEngine/Core/Core.php(111): ExpressionEngine\Core\Core->runController(Array)
#30 <path>/system/ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#31 <path>/index.php(164): require_once('/var/www/natali...')
#32 {main}
```

**Comment by acalvino4** [comment]
If you are telling me that `EE_Template->parse('{!-- ra:0000000...', false, 1, false)` is not a supported use of EE, then like I said we will consider ce cache incompatible. On the other hand if that call is allowed, then seems like EE's code has a php8 compatibility issue, and this issue should be left open.

**Comment by intoeetive** [comment]
Which version of EE are you using? And, what code is on the line of 69 in `ee/legacy/libraries/relationship_parser/VariableFinder.php`?

**Comment by acalvino4** [comment]
We just installed the latest ee upgrade and the error doesn't appear anymore. thanks!
