### ISSUE TITLE
EE2 -> 6.2 Upgrade Breaks ~ version 4.0.5

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#1729]
**Description of the problem**

When upgrading an EE site from v2.11.9 to v6.2.1, the upgrade process dies with a 500 error ~ version 4.0.4.

The upgrade process goes smoothly until reaching version 4.0.4. When attempting to run that upgrade, the browser crashes with a 500 error. I don't get any context on what occurs, and nothing is added to the PHP logs or displayed on screen.

If I upgrade to 6.1.6 first, and then to 6.2.1, the upgrade goes fine.

**How To Reproduce**

1. Get an EEv2.11.9 site.
2. Run typical upgrade steps for an EE2 => EE6 upgrade.

Video walkthrough here: https://youtu.be/CogkgVHnxEI

**Environment Details:**
 - Version: 2.11.9 => 6.2.1
 - PHP Version 7.3
 - MySQL Version 5.7
 - OS: Ubuntu
 - Web Server: nginx

**Possible Solution**

Unfortunately, I don't have much other context. I am not able to see anything in the logs re: to this. Not sure if its related to [this change?](https://github.com/ExpressionEngine/ExpressionEngine/commit/6092aed47865ba6a50708670f997f85ed504a1d7)

**Comment by dougblackjr** [comment]
Turning on debug in admin.php showed this. Stack trace for reference:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jefflilly_p3.exp_channel_data_field_1' doesn't exist:
UPDATE `exp_channel_data_field_1` SET `field_id_1` = ' ' WHERE `field_id_1` = '' OR `field_id_1` IS NULL

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query()
#1 ee/legacy/database/DB_driver.php(260): CI_DB_mysqli_driver->_execute()
#2 ee/legacy/database/DB_driver.php(175): CI_DB_driver->simple_query()
#3 ee/legacy/database/DB_active_rec.php(1388): CI_DB_driver->query()
#4 ee/installer/updates/ud_4_00_05.php(59): CI_DB_active_record->update()
#5 ee/installer/updates/ud_4_00_05.php(34): ExpressionEngine\Updater\Version_4_0_5\Updater->fixGridModifierParsing()
#6 ee/installer/controllers/wizard.php(1234): ExpressionEngine\Updater\Version_4_0_5\Updater->do_update()
#7 ee/installer/controllers/wizard.php(277): Wizard->do_update()
#8 [internal function]: Wizard->_remap()
#9 ee/ExpressionEngine/Core/Core.php(257): call_user_func_array()
#10 ee/ExpressionEngine/Core/Core.php(113): ExpressionEngine\Core\Core->runController()
#11 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run()
#12 admin.php(144): require_once('...')
#13 /home/doug/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('...')
#13 /home/doug/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('...')
