### ISSUE TITLE
Adding DB Column via Query Form results in Duplicate Column exception

### ISSUE THREAD

**Issue by obfuscode** [ExpressionEngine/ExpressionEngine#180]
**Description of the problem**
If you try to add a DB column via the Utilities > Query Form, the column is added but EE throws a Duplicate Column exception.

**How To Reproduce**
1. Paste this into your Query Form:
```sql
ALTER TABLE `exp_cp_log` ADD COLUMN `testing` text NULL;
```
2. Submit Query

**Error Messages**
<pre><code>
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'testing3':
ALTER TABLE `ee5testing`.`exp_cp_log` ADD COLUMN `testing3` text NULL

ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

Stack Trace: Please include when reporting this error

#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('ALTER TABLE `ee...')
#1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('ALTER TABLE `ee...')
#2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('ALTER TABLE `ee...')
#3 ee/EllisLab/ExpressionEngine/Controller/Utilities/Query.php(191): CI_DB_driver->query('ALTER TABLE `ee...')
#4 ee/EllisLab/ExpressionEngine/Controller/Utilities/Query.php(47): EllisLab\ExpressionEngine\Controller\Utilities\Query->runQuery()
#5 [internal function]: EllisLab\ExpressionEngine\Controller\Utilities\Query->index()
#6 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
#7 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
#8 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
#9 admin.php(153): require_once('...')
</code></pre>

**Environment Details:**
 - Version: 5.2.2
 - PHP Version: 7.1
 - MySQL Version: 8.0.12
 - OS: macOS
 - Web Server: nginx

**Additional context**
If the column exists before you run the query, you get EE's clean error alert:
```
Attention: Query not run

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'testing3':<br> ALTER TABLE `ee5testing`.`exp_cp_log` ADD COLUMN `testing3` text NULL
```

**Comment by obfuscode** [comment]
Actually, it looks like all queries in the Query Form are being submitted at least 3 times. Running this query inserts 3 rows!

```sql
INSERT INTO `exp_cp_log` (site_id, member_id, username, act_date, ip_address, action, testing) VALUES (1, 1, 'admin', 1555421516, '127.0.0.1', 'Testing', 'This is a test');
```
