### ISSUE TITLE
Switching from native date field to Event helper date field throws an exception

### ISSUE THREAD

**Issue by shbchk** [ExpressionEngine/ExpressionEngine#1822]
[EE 6.2.4, Event Helper 3.0.4]

Hello!

I am trying to change the existing field type from native Date to Event Helper Date and it throws an exception. Am I allowed to do it?

```
Exception Caught
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP COLUMN `field_dt_68`; check that it exists:
ALTER TABLE `ee6_channel_data` DROP `field_dt_68`
ee/legacy/database/drivers/mysqli/mysqli_connection.php:114

Stack Trace: Please include when reporting this error
#0 sstm\ee\legacy\database\drivers\mysqli\mysqli_driver.php(112): CI_DB_mysqli_connection->query()
#1 sstm\ee\legacy\database\DB_driver.php(260): CI_DB_mysqli_driver->_execute()
#2 sstm\ee\legacy\database\DB_driver.php(175): CI_DB_driver->simple_query()
#3 sstm\ee\legacy\database\DB_forge.php(268): CI_DB_driver->query()
#4 sstm\ee\ExpressionEngine\Model\Content\FieldModel.php(302): CI_DB_forge->drop_column()
#5 sstm\ee\ExpressionEngine\Model\Content\FieldModel.php(251): ExpressionEngine\Model\Content\FieldModel->dropColumns()
#6 sstm\ee\ExpressionEngine\Model\Content\FieldModel.php(175): ExpressionEngine\Model\Content\FieldModel->diffColumns()
#7 [internal function]: ExpressionEngine\Model\Content\FieldModel->onAfterUpdate()
#8 sstm\ee\ExpressionEngine\Service\Model\Model.php(826): call_user_func_array()
#9 sstm\ee\ExpressionEngine\Service\Model\Query\Update.php(50): ExpressionEngine\Service\Model\Model->emit()
#10 sstm\ee\ExpressionEngine\Service\Model\DataStore.php(275): ExpressionEngine\Service\Model\Query\Update->run()
#11 sstm\ee\ExpressionEngine\Service\Model\DataStore.php(240): ExpressionEngine\Service\Model\DataStore->runQuery()
#12 sstm\ee\ExpressionEngine\Service\Model\Query\Builder.php(71): ExpressionEngine\Service\Model\DataStore->updateQuery()
#13 sstm\ee\ExpressionEngine\Service\Model\Model.php(358): ExpressionEngine\Service\Model\Query\Builder->update()
#14 sstm\ee\ExpressionEngine\Model\Content\FieldModel.php(123): ExpressionEngine\Service\Model\Model->save()
#15 sstm\ee\ExpressionEngine\Controller\Fields\Fields.php(356): ExpressionEngine\Model\Content\FieldModel->save()
#16 [internal function]: ExpressionEngine\Controller\Fields\Fields->edit()
#17 sstm\ee\ExpressionEngine\Core\Core.php(257): call_user_func_array()
#18 sstm\ee\ExpressionEngine\Core\Core.php(113): ExpressionEngine\Core\Core->runController()
#19 sstm\ee\ExpressionEngine\Boot\boot.php(161): ExpressionEngine\Core\Core->run()
#20 httpdocs\alfred.php(154): require_once('C:\\OpenServer\\d...')
#20 httpdocs\alfred.php(154): require_once('C:\\OpenServer\\d...') 
```

Addon author, Derek Hogue, [suggested](https://devot-ee.com/add-ons/support/event-helper/viewthread/17078#56343) this is an EE bug and it can be resolved by opening `/system/ee/ExpressionEngine/Addons/date/ft.date.php`, and removing this chunk of code inside of the `settings_modify_column` function.

```
$fields['field_dt_' . $data['field_id']] = array(
    'type' => 'VARCHAR',
    'constraint' => 50
); 
```

**Comment by intoeetive** [comment]
I am going to close this because this is related to third-party add-on which just does not seem to be compatible with Date field (which is very specific because it involved that special `field_dt_X` column)
