### ISSUE TITLE
Channel export error

### ISSUE THREAD

**Issue by stpruss** [ExpressionEngine/ExpressionEngine#237]
**Description of the problem**
Clicking the "Export" button in a Channel in the Channel manager produces an error:

**How To Reproduce**
In my particular example:
Create a channel and add fields to it. In my case I tried one with a Field group with 3 fields in it (Text, URL & File) and another with a Fluid field and several fields applied to it (each grids with multiple fields)

**Error Messages**
Fatal error: Uncaught Error: Call to undefined function EllisLab\ExpressionEngine\Library\Mime\finfo_open() in /home/reshub/public_html/system/ee/EllisLab/ExpressionEngine/Library/Mime/MimeType.php:156 Stack trace: #0 /home/reshub/public_html/system/ee/legacy/libraries/Mime_type.php(109): EllisLab\ExpressionEngine\Library\Mime\MimeType->ofBuffer('PK\x03\x04\x14\x00\x00\x00\x08\x002\x86\xD1N}...') #1 /home/reshub/public_html/system/ee/legacy/helpers/download_helper.php(36): Mime_type->ofBuffer('PK\x03\x04\x14\x00\x00\x00\x08\x002\x86\xD1N}...') #2 /home/reshub/public_html/system/ee/EllisLab/ExpressionEngine/Controller/Channels/Sets.php(124): force_download('ChannelSet.zip', 'PK\x03\x04\x14\x00\x00\x00\x08\x002\x86\xD1N}...') #3 [internal function]: EllisLab\ExpressionEngine\Controller\Channels\Sets->export('1') #4 /home/reshub/public_html/system/ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array) #5 /home/reshub/public_html/system/ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\Exp in /home/reshub/public_html/system/ee/EllisLab/ExpressionEngine/Library/Mime/MimeType.php on line 156
<pre><code>

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 5.2.3
 - PHP Version 7.0.33
 - MySQL Version 10.0.38-MariaDB
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by stpruss** [comment]
Discovered this was a missing PHP extension.
