### ISSUE TITLE
Can't create new field

### ISSUE THREAD

**Issue by inoatech** [ExpressionEngine/ExpressionEngine#293]
**Description of the problem**
I recently upgraded a site from 3.x to the latest version.

**How To Reproduce**
When I create a new field (tested on textarea and toggle types), I receive n SQL error  message that `Field 'group_id' doesn't have a default value`.

**Comment by derekjones** [comment]
What is the full SQL error? Please also provide the stack trace if possible.

**Comment by inoatech** [comment]
Thank you, Derek!

```
SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value:
INSERT INTO `exp_channel_fields` (`field_list_items`, `field_order`, `site_id`, `field_type`, `field_name`, `field_label`, `field_instructions`, `field_ta_rows`, `field_maxl`, `field_required`, `field_search`, `field_is_hidden`, `field_show_fmt`, `field_settings`) VALUES ('', 1, 0, 'toggle', 'departments_showcontacts', 'Show contacts', 'Description.', 6, 256, 'n', 'n', 'n', 'n', 'YToxOntzOjE5OiJmaWVsZF9kZWZhdWx0X3ZhbHVlIjtzOjE6IjEiO30=')
```

If I manually add the `group_id` like this:

``` sql
INSERT INTO `exp_channel_fields` (`group_id`, `field_list_items`, `field_order`, `site_id`, `field_type`, `field_name`, `field_label`, `field_instructions`, `field_ta_rows`, `field_maxl`, `field_required`, `field_search`, `field_is_hidden`, `field_show_fmt`, `field_settings`) VALUES ('7', '', 1, 0, 'toggle', 'departments_showcontacts', 'Show contacts', 'Description', 6, 256, 'n', 'n', 'n', 'n', 'YToxOntzOjE5OiJmaWVsZF9kZWZhdWx0X3ZhbHVlIjtzOjE6IjEiO30=')
```

then I get this error:

``` sql
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.exp_channel_data_field_315' doesn't exist:
SELECT t.entry_id, t.channel_id, t.forum_topic_id, t.author_id, t.ip_address, t.title, t.url_title, t.status, t.view_count_one, t.view_count_two, t.view_count_three, t.view_count_four, t.allow_comments, t.comment_expiration_date, t.sticky, t.entry_date, t.year, t.month, t.day, t.edit_date, t.expiration_date, t.recent_comment_date, t.comment_total, t.site_id as entry_site_id, w.channel_title, w.channel_name, w.channel_url, w.comment_url, w.comment_moderate, w.channel_html_formatting, w.channel_allow_img_urls, w.channel_auto_link_urls, w.comment_system_enabled, m.username, m.email, m.screen_name, m.signature, m.sig_img_filename, m.sig_img_width, m.sig_img_height, m.avatar_filename, m.avatar_width, m.avatar_height, m.photo_filename, m.photo_width, m.photo_height, m.group_id, m.member_id, wd.*, exp_channel_data_field_315.field_id_315, exp_channel_data_field_315.field_ft_315 FROM exp_channel_titles AS t LEFT JOIN exp_channels AS w ON t.channel_id = w.channel_id LEFT JOIN exp_channel_data AS wd ON t.entry_id = wd.entry_id LEFT JOIN exp_members AS m ON m.member_id = t.author_id LEFT JOIN exp_channel_data_field_315 ON t.entry_id = exp_channel_data_field_315.entry_id WHERE t.entry_id IN (1453)ORDER BY FIELD(t.entry_id, 1453)
```

**Comment by inoatech** [comment]
Fuller trace:

```

Exception Caught
SQLSTATE[HY000]: General error: 1364 Field 'group_id' doesn't have a default value:
INSERT INTO `exp_channel_fields` (`field_list_items`, `field_order`, `site_id`, `field_type`, `field_name`, `field_label`, `field_instructions`, `field_ta_rows`, `field_maxl`, `field_required`, `field_text_direction`, `field_search`, `field_is_hidden`, `field_fmt`, `field_show_fmt`, `field_content_type`, `field_settings`) VALUES ('', 1, 0, 'text', 'test_field', 'Test Field', '', 6, 256, 'n', 'ltr', 'n', 'n', 'none', 'n', 'all', 'YTo0OntzOjEwOiJmaWVsZF9tYXhsIjtzOjM6IjI1NiI7czoxODoiZmllbGRfY29udGVudF90eXBlIjtzOjM6ImFsbCI7czoxODoiZmllbGRfc2hvd19zbWlsZXlzIjtzOjE6Im4iO3M6MjQ6ImZpZWxkX3Nob3dfZmlsZV9zZWxlY3RvciI7czoxOiJuIjt9')

ee/legacy/database/drivers/mysqli/mysqli_connection.php:117
Stack Trace: Please include when reporting this error

    #0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('INSERT INTO `ex...')
    #1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('INSERT INTO `ex...')
    #2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('INSERT INTO `ex...')
    #3 ee/legacy/database/DB_active_rec.php(1371): CI_DB_driver->query('INSERT INTO `ex...')
    #4 ee/EllisLab/ExpressionEngine/Service/Model/Query/Insert.php(75): CI_DB_active_record->insert('channel_fields')
    #5 ee/EllisLab/ExpressionEngine/Service/Model/Query/Update.php(99): EllisLab\ExpressionEngine\Service\Model\Query\Insert->actOnGateway(Object(EllisLab\ExpressionEngine\Service\Model\SyntheticGateway), Object(EllisLab\ExpressionEngine\Model\Channel\ChannelField))
    #6 ee/EllisLab/ExpressionEngine/Service/Model/Query/Insert.php(39): EllisLab\ExpressionEngine\Service\Model\Query\Update->doWork(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelField))
    #7 ee/EllisLab/ExpressionEngine/Service/Model/Query/Insert.php(27): EllisLab\ExpressionEngine\Service\Model\Query\Insert->doWork(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelField))
    #8 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(282): EllisLab\ExpressionEngine\Service\Model\Query\Insert->run()
    #9 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(238): EllisLab\ExpressionEngine\Service\Model\DataStore->runQuery('Insert', Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
    #10 ee/EllisLab/ExpressionEngine/Service/Model/Query/Builder.php(79): EllisLab\ExpressionEngine\Service\Model\DataStore->insertQuery(Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
    #11 ee/EllisLab/ExpressionEngine/Service/Model/Model.php(355): EllisLab\ExpressionEngine\Service\Model\Query\Builder->insert()
    #12 ee/EllisLab/ExpressionEngine/Model/Content/FieldModel.php(132): EllisLab\ExpressionEngine\Service\Model\Model->save()
    #13 ee/EllisLab/ExpressionEngine/Controller/Fields/Fields.php(235): EllisLab\ExpressionEngine\Model\Content\FieldModel->save()
    #14 [internal function]: EllisLab\ExpressionEngine\Controller\Fields\Fields->create()
    #15 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
    #16 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
    #17 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
    #18 public/system/index.php(143): require_once('...')
    #18 public/system/index.php(143): require_once('...') 
```

**Comment by derekjones** [comment]
Correct, you should not try to manually add a field to the database, as there are multiple tables involved.

`group_id` isn't a field of that table giving you the error, however, as of 4.0.0. Are you certain you ran the updater on this database? That column is dropped in the 4.0.0 update.

**Comment by inoatech** [comment]
The updater seemed to run fine, jumping me from 3 to 4 to 5. Is there a recommended way to re-run the SQL updates?

**Comment by derekjones** [comment]
If you set the app_version in your config to an older version, it will run them all over again. But I'd probably roll back and start from an unmodified v3 database. I'm also curious what the exp_update_log shows for you.

**Comment by inoatech** [comment]
OK. I don't have the luxury of going back, but I did run the installer and step through everything from 3.1 on. Things seemed to go smoothly. Nothing juicy in the `update.log` file. In the `exp_update_log` table I just see a bunch of `Could not create table...Table already exists.` which I would expect — nothing else seems too interesting.

I tried creating another field and received the same error:

``` sql
eneral error: 1364 Field 'group_id' doesn't have a default value:
INSERT INTO `exp_channel_fields` (`field_list_items`, `field_order`, `site_id`, `field_type`, `field_name`, `field_label`, `field_instructions`, `field_ta_rows`, `field_maxl`, `field_required`, `field_text_direction`, `field_search`, `field_is_hidden`, `field_fmt`, `field_show_fmt`, `field_content_type`, `field_settings`) VALUES ('', 1, 0, 'text', 'test_field', 'Test field', '', 6, 256, 'n', 'ltr', 'n', 'n', 'none', 'n', 'all', 'YTo0OntzOjEwOiJmaWVsZF9tYXhsIjtzOjM6IjI1NiI7czoxODoiZmllbGRfY29udGVudF90eXBlIjtzOjM6ImFsbCI7czoxODoiZmllbGRfc2hvd19zbWlsZXlzIjtzOjE6Im4iO3M6MjQ6ImZpZWxkX3Nob3dfZmlsZV9zZWxlY3RvciI7czoxOiJuIjt9')
```

**Comment by Bright-Wing-Media** [comment]
The only mention I see of `channel_fields.group_id` is in `updates/ud_4_00_00.php`. In `mod.channel.php` I see line 731: `$table = (isset($legacy_fields[$field_id])) ? "wd" : "exp_channel_data_field_{$field_id}";` (I was curious where that `channel_data_field_` error was coming from.

Hopefully, we'll get to meet in person at the upcoming EEConf.

**Comment by inoatech** [comment]
The only mention I see of channel_fields.group_id is in updates/ud_4_00_00.php. In mod.channel.php I see line 731: $table = (isset($legacy_fields[$field_id])) ? "wd" : "exp_channel_data_field_{$field_id}"; (I was curious where that channel_data_field_ error was coming from.

Hopefully, we'll get to meet in person at the upcoming EEConf.

**Comment by derekjones** [comment]
Correct, that mention in 4.0.0's update file is where the column [is dropped](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/system/ee/installer/updates/ud_4_00_00.php#L182). I'm not sure why rolling back isn't an option—this makes me distrust the integrity of your database—but you could certainly always try manually dropping that column if you must. Does the update log table show that you successfully stepped through all of v4's updates?

**Comment by inoatech** [comment]
Derek,

_Success_. I manually dropped the column and can now create fields. Thank you.

Rolling back - too many changes in the interim.

I am attaching here a full dump of the update_log column as CSV.

[exp_update_log.txt](https://github.com/ExpressionEngine/ExpressionEngine/files/3535486/exp_update_log.txt)

**Comment by intoeetive** [comment]
Since the issue has been resolved for OP and it does not appear to be general code problem, closing this out
