### ISSUE TITLE
Channel entries show SQL error if category tied to it has more than 75 categories

### ISSUE THREAD

**Issue by marketingalliance** [ExpressionEngine/ExpressionEngine#316]
**Description of the problem**

I have a channel for a members directory that gets sorted by categories. My client added category #76 to the list, and the channel went haywire. If I remove that category to get the coung back to 75, it works fine.

**How To Reproduce**
1. Create a channel.
2. Create a category group.
3. Assign that category group to the channel.
4. Add 75 categories and see if you can create an entry.
5. Now add one more and see if you can create or edit an entry.

**Error Messages**

<pre><code>

Exception Caught
SQLSTATE[42000]: Syntax error or access violation: 1104 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay:
SELECT Category_categories.cat_id as Category__cat_id, Category_categories.site_id as Category__site_id, Category_categories.group_id as Category__group_id, Category_categories.parent_id as Category__parent_id, Category_categories.cat_name as Category__cat_name, Category_categories.cat_url_title as Category__cat_url_title, Category_categories.cat_description as Category__cat_description, Category_categories.cat_image as Category__cat_image, Category_categories.cat_order as Category__cat_order, Category_category_field_data.cat_id as Category__cat_id, Category_category_field_data.site_id as Category__site_id, Category_category_field_data.group_id as Category__group_id, Category_category_field_data.cat_id as Category__cat_id, Category_category_field_data.site_id as Category__site_id, Category_category_field_data.group_id as Category__group_id, C0_categories.cat_id as C0__cat_id, C0_categories.site_id as C0__site_id, C0_categories.group_id as C0__group_id, C0_categories.parent_id as C0__parent_id, C0_categories.cat_name as C0__cat_name, C0_categories.cat_url_title as C0__cat_url_title, C0_categories.cat_description as C0__cat_description, C0_categories.cat_image as C0__cat_image, C0_categories.cat_order as C0__cat_order, C0_category_field_data.cat_id as C0__cat_id, C0_category_field_data.site_id as C0__site_id, C0_category_field_data.group_id as C0__group_id, C0_category_field_data.cat_id as C0__cat_id, C0_category_field_data.site_id as C0__site_id, C0_category_field_data.group_id as C0__group_id, C1_categories.cat_id as C1__cat_id, C1_categories.site_id as C1__site_id, C1_categories.group_id as C1__group_id, C1_categories.parent_id as C1__parent_id, C1_categories.cat_name as C1__cat_name, C1_categories.cat_url_title as C1__cat_url_title, C1_categories.cat_description as C1__cat_description, C1_categories.cat_image as C1__cat_image, C1_categories.cat_order as C1__cat_order, C1_category_field_data.cat_id as C1__cat_id, C1_category_field_data.site_id as C1__site_id, C1_category_field_data.group_id as C1__group_id, C1_category_field_data.cat_id as C1__cat_id, C1_category_field_data.site_id as C1__site_id, C1_category_field_data.group_id as C1__group_id, C2_categories.cat_id as C2__cat_id, C2_categories.site_id as C2__site_id, C2_categories.group_id as C2__group_id, C2_categories.parent_id as C2__parent_id, C2_categories.cat_name as C2__cat_name, C2_categories.cat_url_title as C2__cat_url_title, C2_categories.cat_description as C2__cat_description, C2_categories.cat_image as C2__cat_image, C2_categories.cat_order as C2__cat_order, C2_category_field_data.cat_id as C2__cat_id, C2_category_field_data.site_id as C2__site_id, C2_category_field_data.group_id as C2__group_id, C2_category_field_data.cat_id as C2__cat_id, C2_category_field_data.site_id as C2__site_id, C2_category_field_data.group_id as C2__group_id, C3_categories.cat_id as C3__cat_id, C3_categories.site_id as C3__site_id, C3_categories.group_id as C3__group_id, C3_categories.parent_id as C3__parent_id, C3_categories.cat_name as C3__cat_name, C3_categories.cat_url_title as C3__cat_url_title, C3_categories.cat_description as C3__cat_description, C3_categories.cat_image as C3__cat_image, C3_categories.cat_order as C3__cat_order, C3_category_field_data.cat_id as C3__cat_id, C3_category_field_data.site_id as C3__site_id, C3_category_field_data.group_id as C3__group_id, C3_category_field_data.cat_id as C3__cat_id, C3_category_field_data.site_id as C3__site_id, C3_category_field_data.group_id as C3__group_id, CategoryGroup_category_groups.group_id as CategoryGroup__group_id, CategoryGroup_category_groups.site_id as CategoryGroup__site_id, CategoryGroup_category_groups.group_name as CategoryGroup__group_name, CategoryGroup_category_groups.sort_order as CategoryGroup__sort_order, CategoryGroup_category_groups.exclude_group as CategoryGroup__exclude_group, CategoryGroup_category_groups.field_html_formatting as CategoryGroup__field_html_formatting, CategoryGroup_category_groups.can_edit_categories as CategoryGroup__can_edit_categories, CategoryGroup_category_groups.can_delete_categories as CategoryGroup__can_delete_categories FROM (`exp_categories` as Category_categories, `exp_category_field_data` as Category_category_field_data) LEFT JOIN `exp_categories` AS C0_categories ON `C0_categories`.`parent_id` = `Category_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C0_category_field_data ON `C0_category_field_data`.`cat_id` = `C0_categories`.`cat_id` LEFT JOIN `exp_categories` AS C1_categories ON `C1_categories`.`parent_id` = `C0_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C1_category_field_data ON `C1_category_field_data`.`cat_id` = `C1_categories`.`cat_id` LEFT JOIN `exp_categories` AS C2_categories ON `C2_categories`.`parent_id` = `C1_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C2_category_field_data ON `C2_category_field_data`.`cat_id` = `C2_categories`.`cat_id` LEFT JOIN `exp_categories` AS C3_categories ON `C3_categories`.`parent_id` = `C2_categories`.`cat_id` LEFT JOIN `exp_category_field_data` as C3_category_field_data ON `C3_category_field_data`.`cat_id` = `C3_categories`.`cat_id` LEFT JOIN `exp_category_groups` AS CategoryGroup_category_groups ON `CategoryGroup_category_groups`.`group_id` = `Category_categories`.`group_id` WHERE Category_category_field_data.cat_id = Category_categories.cat_id AND ( `CategoryGroup_category_groups`.`group_id` = 1 AND `Category_categories`.`parent_id` = 0 ) LIMIT 18446744073709551615

ee/legacy/database/drivers/mysqli/mysqli_connection.php:117

Stack Trace: Please include when reporting this error

    #0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('SELECT Category...')
    #1 ee/legacy/database/DB_driver.php(270): CI_DB_mysqli_driver->_execute('SELECT Category...')
    #2 ee/legacy/database/DB_driver.php(180): CI_DB_driver->simple_query('SELECT Category...')
    #3 ee/legacy/database/DB_active_rec.php(1138): CI_DB_driver->query('SELECT Category...')
    #4 ee/EllisLab/ExpressionEngine/Service/Model/Query/Select.php(50): CI_DB_active_record->get()
    #5 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(282): EllisLab\ExpressionEngine\Service\Model\Query\Select->run()
    #6 ee/EllisLab/ExpressionEngine/Service/Model/DataStore.php(228): EllisLab\ExpressionEngine\Service\Model\DataStore->runQuery('Select', Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
    #7 ee/EllisLab/ExpressionEngine/Service/Model/Query/Builder.php(144): EllisLab\ExpressionEngine\Service\Model\DataStore->selectQuery(Object(EllisLab\ExpressionEngine\Service\Model\Query\Builder))
    #8 ee/EllisLab/ExpressionEngine/Service/Model/Query/Builder.php(63): EllisLab\ExpressionEngine\Service\Model\Query\Builder->fetch()
    #9 ee/EllisLab/ExpressionEngine/Model/Category/CategoryGroup.php(212): EllisLab\ExpressionEngine\Service\Model\Query\Builder->all()
    #10 [internal function]: EllisLab\ExpressionEngine\Model\Category\CategoryGroup->populateCategories(Object(EllisLab\ExpressionEngine\Model\Content\FieldFacade))
    #11 ee/EllisLab/ExpressionEngine/Model/Content/FieldFacade.php(105): call_user_func(Array, Object(EllisLab\ExpressionEngine\Model\Content\FieldFacade))
    #12 ee/EllisLab/ExpressionEngine/Model/Content/FieldFacade.php(332): EllisLab\ExpressionEngine\Model\Content\FieldFacade->ensurePopulatedDefaults()
    #13 ee/EllisLab/ExpressionEngine/Model/Content/FieldFacade.php(265): EllisLab\ExpressionEngine\Model\Content\FieldFacade->initField()
    #14 ee/EllisLab/ExpressionEngine/Model/Content/Display/FieldDisplay.php(60): EllisLab\ExpressionEngine\Model\Content\FieldFacade->getStatus()
    #15 ee/EllisLab/ExpressionEngine/View/publish/partials/publish_form.php(46): EllisLab\ExpressionEngine\Model\Content\Display\FieldDisplay->getStatus()
    #16 ee/EllisLab/ExpressionEngine/Service/View/View.php(134): include('...')
    #17 ee/EllisLab/ExpressionEngine/Service/View/View.php(99): EllisLab\ExpressionEngine\Service\View\View->parse('...', Array)
    #18 ee/EllisLab/ExpressionEngine/Service/View/View.php(157): EllisLab\ExpressionEngine\Service\View\View->render(Array)
    #19 ee/EllisLab/ExpressionEngine/View/publish/entry.php(3): EllisLab\ExpressionEngine\Service\View\View->embed(Object(EllisLab\ExpressionEngine\Service\View\View))
    #20 ee/EllisLab/ExpressionEngine/Service/View/View.php(134): include('...')
    #21 ee/EllisLab/ExpressionEngine/Service/View/View.php(99): EllisLab\ExpressionEngine\Service\View\View->parse('...', Array)
    #22 ee/legacy/libraries/View.php(40): EllisLab\ExpressionEngine\Service\View\View->render(Array)
    #23 ee/legacy/libraries/Cp.php(257): View->render('publish/entry', Array, false)
    #24 ee/EllisLab/ExpressionEngine/Controller/Publish/Edit.php(555): Cp->render('publish/entry', Array)
    #25 [internal function]: EllisLab\ExpressionEngine\Controller\Publish\Edit->entry('760')
    #26 ee/EllisLab/ExpressionEngine/Core/Core.php(241): call_user_func_array(Array, Array)
    #27 ee/EllisLab/ExpressionEngine/Core/Core.php(110): EllisLab\ExpressionEngine\Core\Core->runController(Array)
    #28 ee/EllisLab/ExpressionEngine/Boot/boot.php(151): EllisLab\ExpressionEngine\Core\Core->run(Object(EllisLab\ExpressionEngine\Core\Request))
    #29 public_html/admin_stlucie.php(153): require_once('...')
    #29 public_html/admin_stlucie.php(153): require_once('...') 

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: [e.g. 5.0.1]
 - PHP Version [e.g. 7.1]
 - MySQL Version [e.g. 5.7]
 - OS: [e.g. Linux, macOS, Windows]
 - Web Server: [e.g. Apache, nginx, MAMP, etc.]

**Possible Solution**

**Additional context**

**Comment by derekjones** [comment]
Along with #314 it sounds like you might have some environmental issues. What are your MySQL server settings for MAX_JOIN_SIZE and SQL_BIG_SELECTS?

**Comment by marketingalliance** [comment]
sql_big_selects is OFF
max_join_size is 1000000000

**Comment by derekjones** [comment]
Is this category group deeply nested? Have you looked to see if it's an efficient information architecture for how the client is using categories? Turning `sql_big_selects` on would be an instant fix, but it's worth taking a look at the IA while you're there. That's a MySQL setting to prevent accidentally large queries. The WHERE clause in this cause is a bit vague (to MySQL's optimizer) even though in reality to ExpressionEngine it's not, it's just populating that category menu with all categories that belong to this channel, and isn't actually going to end up examining a billion rows.

**Comment by intoeetive** [comment]
Quite an old issue, and while we weren't able to replicate it - the query to fetch the categories that's being run on CP Entry page is the same.

IDK if that would solve the issue, but it looks like the query can be optimized - since there are no custom fields for categories, there's no obvious reason to perform join on `category_field_data` table

**Comment by intoeetive** [comment]
The optimization that will likely fix it is getting released in EE 7.4.0
