### ISSUE TITLE
EE6 Fluid field Live Preview, Call to a member function getField() on null

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#3225]
Error Caught Call to a member function getField() on null

ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php:157 

```
#0 ee/ExpressionEngine/Service/LivePreview/LivePreview.php(116): Fluid_field_ft->save(Array)
#1 ee/ExpressionEngine/Addons/channel/mod.channel.php(5226): ExpressionEngine\Service\LivePreview\LivePreview->preview('8', '186', NULL, false)
#2 ee/legacy/libraries/Actions.php(175): Channel->live_preview()
#3 ee/legacy/libraries/Core.php(657): EE_Actions->__construct(true, Object(Closure))
#4 ee/legacy/controllers/ee.php(51): EE_Core->generate_action(true)
#5 [internal function]: EE->index()
#6 ee/ExpressionEngine/Core/Core.php(266): call_user_func_array(Array, Array)
#7 ee/ExpressionEngine/Core/Core.php(122): ExpressionEngine\Core\Core->runController(Array)
#8 ee/ExpressionEngine/Boot/boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#9 index.php(173): require_once('...')
#9 index.php(173): require_once('...') 
```

**Comment by intoeetive** [comment]
Oops, we forgot to release fix for EE6 that we released for EE 7
