### ISSUE TITLE
Fatal Error & data loss when deleting a member and re-assigning entries to another user

### ISSUE THREAD

**Issue by pyrobob83** [ExpressionEngine/ExpressionEngine#380]
Discovered when a client tried to delete a CMS user who had authored various entries and even when they re-assigned the entries to another user, all the entries authored by the deleted user still were deleted.

After testing in DEV, I got this Fatal Error:

```Fatal error: Uncaught Error: Call to a member function updateAuthorStats() on null in /home/domains/client.com/system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php:516 Stack trace: #0 [internal function]: EllisLab\ExpressionEngine\Model\Channel\ChannelEntry->onAfterDelete() #1 /home/domains/client.com/system/ee/EllisLab/ExpressionEngine/Service/Model/Model.php(825): call_user_func_array(Array, Array) #2 [internal function]: EllisLab\ExpressionEngine\Service\Model\Model->emit('afterDelete') #3 /home/domains/client.com/system/ee/EllisLab/ExpressionEngine/Library/Data/Collection.php(86): call_user_func_array(Array, Array) #4 [internal function]: EllisLab\ExpressionEngine\Library\Data\Collection->EllisLab\ExpressionEngine\Library\Data\{closure}(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry)) #5 /home/domains/client.com/system/ee/EllisLab/ExpressionEngine/Library/Data/Collection.php(245): array_map(Object(Closure), Array) #6 /home/investme/ in /home/domains/client.com/system/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php on line 516```

But the user *was* deleted along with all their entries (ie, entries were *not* reassigned).

Bizarre thing is that I tried in a different environment with different plugins and it works just fine, so I figured it might be a conflict with an add-on... after several rollbacks and trial-and-error testing, it works fine if I uninstall Visitor, but happens every time with Visitor - so I guess this is a Visitor issue, not EE.

However, it's worth mentioning Brian Litzinger said he had this same issue around a year ago and opened a bug in the old bug tracker, but he thought it got fixed.  His site didn't use Visitor though, so perhaps it got fixed for native, but Visitor is reintroducing it somehow.

**Comment by pyrobob83** [comment]
Closing issue as this is more a Visitor issue rather than EE
