### ISSUE TITLE
Call to undefined function iconv_strlen()

### ISSUE THREAD

**Issue by dougblackjr** [ExpressionEngine/ExpressionEngine#406]
**Description of the problem**
As reported on EE Slack:
Upgraded to 5.3.1 and on saving an edited entry I get this error:
`Fatal error: Uncaught Error: Call to undefined function iconv_strlen()`

Stack Trace:
```
Fatal error: Uncaught Error: Call to undefined function iconv_strlen() in /home/altereds/sys/ee/legacy/helpers/multibyte_helper.php:84
Stack trace:
#0 /home/xxx/sys/ee/EllisLab/ExpressionEngine/Service/Validation/Rule/MaxLength.php(34): ee_mb_strlen(NULL)
#1 /home/xxx/sys/ee/EllisLab/ExpressionEngine/Service/Validation/Validator.php(186): EllisLab\ExpressionEngine\Service\Validation\Rule\MaxLength->validate(‘title’, NULL)
#2 /home/xxx/sys/ee/EllisLab/ExpressionEngine/Service/Validation/Validator.php(147): EllisLab\ExpressionEngine\Service\Validation\Validator->_validate(Array, true)
#3 /home/xxx/sys/ee/EllisLab/ExpressionEngine/Service/Model/Model.php(485): EllisLab\ExpressionEngine\Service\Validation\Validator->validatePartial(Object(EllisLab\ExpressionEngine\Model\Channel\ChannelEntry))
#4 /home/xxx/sys/ee/EllisLab/ExpressionEngine/Model/Channel/ChannelEntry.php(216): EllisLab\ExpressionEngine\Service\Model\Model->validate()
#5 /home/xxx/sys/ee/EllisLab/ExpressionEngine/Controller/Publish/A in /home/xxx/sys/ee/legacy/helpers/multibyte_helper.php on line 84
```

**Environment Details:**
 - Version: 5.3.1
 - PHP Version Any without iconv installed

**Possible Solution**
Ensure iconv extension is installed and enabled.

**Comment by ops-andy** [comment]
for reference this was reported in Slack: https://eecms.slack.com/archives/C04CUNNR9/p1587038129071800
