### ISSUE TITLE
SQL Error when using the remove button in structure

### ISSUE THREAD

**Issue by rbroadford** [ExpressionEngine/ExpressionEngine#4135]
When you try to remove a page(s) with children in structure (using the remove button) = this SQL error

`Exception Caught
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND site_id = 1' at line 4:
UPDATE exp_structure SET lft = lft + 2 WHERE lft >= AND site_id = 1
ee/legacy/database/drivers/mysqli/mysqli_connection.php:146

Stack Trace: Please include when reporting this error
#0 ee/legacy/database/drivers/mysqli/mysqli_driver.php(112): CI_DB_mysqli_connection->query('UPDATE exp_stru...')
#1 ee/legacy/database/DB_driver.php(262): CI_DB_mysqli_driver->_execute('UPDATE exp_stru...')
#2 ee/legacy/database/DB_driver.php(177): CI_DB_driver->simple_query('UPDATE exp_stru...')
#3 ee/ExpressionEngine/Addons/structure/libraries/nestedset/structure_nestedset_adapter_ee.php(229): CI_DB_driver->query('UPDATE exp_stru...')
#4 ee/ExpressionEngine/Addons/structure/libraries/nestedset/structure_nestedset.php(19): Structure_Nestedset_Adapter_Ee->shift(NULL, 2)
#5 ee/ExpressionEngine/Addons/structure/mod.structure.php(1241): Structure_Nestedset->newLastChild(NULL, Array)
#6 ee/ExpressionEngine/Addons/structure/tab.structure.php(625): Structure->set_data(Array, true)
#7 ee/ExpressionEngine/Addons/structure/tab.structure.php(396): Structure_tab->publish_data_db(Array, Object(ExpressionEngine\Addons\Pro\Model\Channel\ChannelEntry))
#8 ee/ExpressionEngine/Model/Channel/ChannelEntry.php(659): Structure_tab->save(Object(ExpressionEngine\Addons\Pro\Model\Channel\ChannelEntry), Array)
#9 ee/ExpressionEngine/Model/Channel/ChannelEntry.php(496): ExpressionEngine\Model\Channel\ChannelEntry->saveTabData()
#10 [internal function]: ExpressionEngine\Model\Channel\ChannelEntry->onAfterSave()
#11 ee/ExpressionEngine/Service/Model/Model.php(840): call_user_func_array(Array, Array)
#12 ee/ExpressionEngine/Service/Model/Query/Update.php(49): ExpressionEngine\Service\Model\Model->emit('afterSave')
#13 ee/ExpressionEngine/Service/Model/DataStore.php(275): ExpressionEngine\Service\Model\Query\Update->run()
#14 ee/ExpressionEngine/Service/Model/DataStore.php(240): ExpressionEngine\Service\Model\DataStore->runQuery('Update', Object(ExpressionEngine\Service\Model\Query\Builder))
#15 ee/ExpressionEngine/Service/Model/Query/Builder.php(72): ExpressionEngine\Service\Model\DataStore->updateQuery(Object(ExpressionEngine\Service\Model\Query\Builder))
#16 ee/ExpressionEngine/Service/Model/Model.php(370): ExpressionEngine\Service\Model\Query\Builder->update()
#17 ee/ExpressionEngine/Model/Content/ContentModel.php(219): ExpressionEngine\Service\Model\Model->save()
#18 ee/ExpressionEngine/Addons/structure/mod.structure.php(1961): ExpressionEngine\Model\Content\ContentModel->save()
#19 ee/ExpressionEngine/Addons/structure/mcp.structure.php(857): Structure->delete_data(Array)
#20 [internal function]: Structure_mcp->delete()
#21 ee/ExpressionEngine/Controller/Addons/Addons.php(1590): call_user_func_array(Array, Array)
#22 ee/ExpressionEngine/Controller/Addons/Addons.php(866): ExpressionEngine\Controller\Addons\Addons->getModuleSettings('structure', 'delete', Array)
#23 [internal function]: ExpressionEngine\Controller\Addons\Addons->settings('structure', 'delete')
#24 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
#25 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController(Array)
#26 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#27 admin.php(139): require_once('...')
#27 admin.php(139): require_once('...')`

**Comment by rbroadford** [comment]
EE: 7.4.2
PHP: 8.2
