### ISSUE TITLE
EE_Relationship_exception Caught

### ISSUE THREAD

**Issue by marketingalliance** [ExpressionEngine/ExpressionEngine#4337]
**Description of the problem**
Experiencing an error when you use the search functionality

**How To Reproduce**
1. Go to https://chooseweatherford.com
2. Click on the Search icon to pull up the Advanced Search module
3. Search for anything. I tried "Weatherford", since this is a site for Weatherford, TX
4. See error below.

**Error Messages**

<pre><code>

EE_Relationship_exception Caught
Unmatched Relationship Tag: "{content}"

ee/legacy/libraries/relationship_parser/Tree_builder.php:389
Stack Trace: Please include when reporting this error

    #0 ee/legacy/libraries/relationship_parser/Tree_builder.php(80): EE_relationship_tree_builder->_build_tree('\n\t <div>\n\t\t ...')
    #1 ee/legacy/libraries/Relationships_parser.php(115): EE_relationship_tree_builder->build_tree(Array, '\n\t <div>\n\t\t ...')
    #2 ee/ExpressionEngine/Addons/fluid_field/Service/Tag.php(126): EE_Relationships_parser->create(Array, Array, '\n\t <div>\n\t\t ...', Array, NULL, 71)
    #3 ee/legacy/libraries/Fluid_field_parser.php(439): ExpressionEngine\Addons\FluidField\Service\Tag->parse(Object(ExpressionEngine\Model\Content\FieldFacade), Array)
    #4 ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php(1086): Fluid_field_parser->parse(Array, 83, Array, '{page_content:b...', 'channel')
    #5 ee/legacy/libraries/api/Api_channel_fields.php(444): Fluid_field_ft->replace_tag('Transportation ...', Array, '{page_content:b...')
    #6 ee/legacy/libraries/channel_entries_parser/components/Custom_field_pair.php(183): Api_channel_fields->apply('replace_tag', Array)
    #7 ee/legacy/libraries/channel_entries_parser/Parser.php(291): EE_Channel_custom_field_pair_parser->replace('\n\t <div>\n\t\t ...', Object(EE_Channel_data_parser), Array)
    #8 ee/legacy/libraries/Channel_entries_parser.php(172): EE_Channel_data_parser->parse(Array, Array)
    #9 ee/ExpressionEngine/Addons/channel/mod.channel.php(2543): EE_Channel_parser->parse(Object(Channel), Array, Array)
    #10 ee/ExpressionEngine/Addons/search/mod.search.php(1274): Channel->parse_channel_entries(Array)
    #11 ee/legacy/libraries/Template.php(1835): Search->search_results()
    #12 ee/legacy/libraries/Template.php(1510): EE_Template->process_tags()
    #13 ee/legacy/libraries/Template.php(625): EE_Template->tags()
    #14 ee/legacy/libraries/Template.php(248): EE_Template->parse('{!-- ra:0000000...', false, 1, false)
    #15 ee/legacy/libraries/Template.php(178): EE_Template->fetch_and_parse('', '', false)
    #16 ee/legacy/libraries/Core.php(811): EE_Template->run_template_engine('', '')
    #17 ee/legacy/controllers/ee.php(53): EE_Core->generate_page()
    #18 [internal function]: EE->index()
    #19 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array(Array, Array)
    #20 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController(Array)
    #21 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
    #22 public_html/index.php(164): require_once('...')
    #22 public_html/index.php(164): require_once('...') 

</code></pre>

**Screenshots / Videos / Template Code**

**Environment Details:**
 - Version: 7.4.10
 - PHP Version 7.3
 - MySQL Version 5.2.1
 - OS: Linux
 - Web Server: Apache

**Possible Solution**

**Additional context**

**Comment by TomJaeger** [comment]
Thanks for posting this.  Site looks great!

Based on the error above. It looks like there might be an issue with the template.  Any chance this started happening when building out a specific part of the results template?  If so, any details you could provide would be greatly appreciated!

**Comment by marketingalliance** [comment]
No, we've had this in place for at least a year. I've used the same results code for hundreds of sites at this point. And it's odd. You can search for "test" and it yields results.
