### ISSUE TITLE
Call to a member function getAllCustomFields() on null

### ISSUE THREAD

**Issue by rpickart** [ExpressionEngine/ExpressionEngine#4411]
Hi,

I updated EE from 7.2.12 to 7.4.11 via one-click updater.

Now I am getting the following error when I click on the "Entries" link in the controlpanel:

Call to a member function getAllCustomFields() on null
ee/ExpressionEngine/Model/Content/ContentModel.php:493

Stack Trace: Please include when reporting this error
#0 ee/ExpressionEngine/Model/Content/ContentModel.php(103): ExpressionEngine\Model\Content\ContentModel->deleteFieldData()
#1 ee/ExpressionEngine/Model/Channel/ChannelEntry.php(600): ExpressionEngine\Model\Content\ContentModel->onBeforeDelete()
#2 [internal function]: ExpressionEngine\Model\Channel\ChannelEntry->onBeforeDelete()
#3 ee/ExpressionEngine/Service/Model/Model.php(840): call_user_func_array()

I can still list entries for a specific channel just not the unfiltered view.

EE version 7.4.11
PHP 8.0.27
MySQL 8.0.30

**Comment by intoeetive** [comment]
@rpickart as a quick fix, you can comment out / remove line 192 in `system\ee\ExpressionEngine\Controller\Publish\Edit.php` that says `$entry->delete();`
We'll be working on long-term fix meanwhile

**Comment by rpickart** [comment]
Thanks!
