### ISSUE TITLE
Weird validation related error - grid field with conditional display

### ISSUE THREAD

**Issue by jcogs-design** [ExpressionEngine/ExpressionEngine#4432]
**Description of the problem**
Have a multi-element grid field that is shown / hidden based on the value of a conditional toggle.
If the grid field is "conditionally hidden" entries in the channel can be saved without problem.
If the grid field is "conditionally shown" any attempt to save the entry triggers the exception error.
Oddly, the exception error relates to fluid field code, even though the field concerned is not within a fluid field.

The screen shots show the evolution of the setup:

- The fields defined for the channel concerned
- The detailed definition information for the "Hero Video" grid field that appears to be the cause of the error
- A view of the channel entry before saving withe hero grid 'showing'
- A view of the channel entry upon saving.

In the example there was no data in the grid field - and since one of the grid elements is 'required' EE should have thrown a validation error.

**Error Messages**

<pre><code>
Warning
Undefined array key 29

ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php, line 653

    Severity: E_WARNING

Error Caught
__clone method called on non-object

ee/ExpressionEngine/Addons/fluid_field/ft.fluid_field.php:653
Stack Trace: Please include when reporting this error

    #0 ee/legacy/fieldtypes/EE_Fieldtype.php(325): Fluid_field_ft->display_field()
    #1 ee/legacy/libraries/api/Api_channel_fields.php(444): EE_Fieldtype->display_publish_field()
    #2 ee/ExpressionEngine/Model/Content/FieldFacade.php(292): Api_channel_fields->apply()
    #3 ee/ExpressionEngine/Model/Content/Display/FieldDisplay.php(83): ExpressionEngine\Model\Content\FieldFacade->getForm()
    #4 ee/ExpressionEngine/View/publish/partials/publish_form.php(135): ExpressionEngine\Model\Content\Display\FieldDisplay->getForm()
    #5 ee/ExpressionEngine/Service/View/View.php(137): include('...')
    #6 ee/ExpressionEngine/Service/View/View.php(106): ExpressionEngine\Service\View\View->parse()
    #7 ee/ExpressionEngine/Service/View/View.php(165): ExpressionEngine\Service\View\View->render()
    #8 ee/ExpressionEngine/View/publish/entry.php(5): ExpressionEngine\Service\View\View->embed()
    #9 ee/ExpressionEngine/Service/View/View.php(137): include('...')
    #10 ee/ExpressionEngine/Service/View/View.php(106): ExpressionEngine\Service\View\View->parse()
    #11 ee/legacy/libraries/View.php(40): ExpressionEngine\Service\View\View->render()
    #12 ee/legacy/libraries/Cp.php(344): View->render()
    #13 ee/ExpressionEngine/Controller/Publish/Edit.php(562): Cp->render()
    #14 [internal function]: ExpressionEngine\Controller\Publish\Edit->entry()
    #15 ee/ExpressionEngine/Core/Core.php(268): call_user_func_array()
    #16 ee/ExpressionEngine/Core/Core.php(124): ExpressionEngine\Core\Core->runController()
    #17 ee/ExpressionEngine/Boot/boot.php(184): ExpressionEngine\Core\Core->run()
    #18 public_html/admin.php(139): require_once('...')
    #18 public_html/admin.php(139): require_once('...') 
</code></pre>

**Screenshots / Videos / Template Code**
![image](https://github.com/user-attachments/assets/441a5afe-f861-4598-9748-5d516abf827b)
![image](https://github.com/user-attachments/assets/636c0b52-589c-469a-bf02-8514aedd02f7)
![image](https://github.com/user-attachments/assets/1369120f-505a-4fdd-8953-d83c77918d62)
![image](https://github.com/user-attachments/assets/dc4bbab1-8257-4d6d-a2bc-13fb15438137)

**Environment Details:**
 - Version: 7.4.11
 - PHP Version 8.3.10

**Comment by intoeetive** [comment]
@jcogs-design any idea on what `29` could stand for? That's ID of one of the fields, but which one? Also, is that Grid also reused as part of Fluid - directly or via field groups?
