### ISSUE TITLE
Structure nav tag Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4442]
```
Object of class DateTime could not be converted to string

ee/legacy/libraries/Localize.php:257

Stack Trace: Please include when reporting this error

#0 ee/legacy/libraries/Localize.php(90): Localize->_datetime()
#1 ee/legacy/libraries/Template.php(4264): Localize->format_date()
#2 ee/legacy/libraries/Template.php(4187): EE_Template->process_date()
#3 ee/legacy/libraries/Template.php(3875): EE_Template->parse_date_variables()
#4 ee/legacy/libraries/Template.php(3796): EE_Template->_parse_var_single()
#5 ee/legacy/libraries/Template.php(3724): EE_Template->parse_variables_row()
#6 ee/ExpressionEngine/Addons/structure/mod.structure.php(2125): EE_Template->parse_variables()
#7 ee/ExpressionEngine/Addons/structure/mod.structure.php(2132): Structure->nav_basic()
#8 ee/legacy/libraries/Template.php(1835): Structure->nav_advanced()
```
Using tag:

```
{exp:structure:nav_advanced show_depth="4"}
<url>
   <loc>{root:page_url}</loc>
   <lastmod>{root:edit_date format="%Y-%m-%dT%H:%i:%s-05:00"}</lastmod>
   <changefreq>weekly</changefreq>
   <priority>0.5</priority>
</url>
{/exp:structure:nav_advanced}
```

Poking around, Structure is using the channelentry model to pull back data, and entry_edit_date and comment_edit_date are coming back as datetime objects, while the other dates are integers.  And then when it sends the dates over to be parsed, Localize is choking on it.  I added a check for $date_string being a date time object, and this appears to work.  But I'm not sure that's where the fix should be.  I also don't fully get why it doesn't choke an entry tag or anything else I can see- but I don't specifically spot where Structure itself is doing something weird.  SO... here is an open bug.

```
    private function _datetime($date_string = null, $timezone = true, $date_format = null)
    {

	if ($date_string instanceof DateTime) { $date_string = $date_string->getTimestamp(); }
		
        // Checking for ambiguous dates but only when we don't have a date
        // format.
        if (! $date_format) {
				
            if (preg_match('/\b\d{1,2}-\d{1,2}-\d{2}\b/', (string) $date_string)) {
                return false;
            }
 
```

**Comment by intoeetive** [comment]
@robinsowell I'd say, if it works - keep it (and open a PR)

Remember we still need to solve the issue with INT fields not being able to hold dates past 2035, so it might as well be a good idea to have all dates as DateTime 

But for now, I think the fix is fine
