### ISSUE TITLE
Exceptions show_error can throw a Fatal error: Uncaught Error: Undefined constant "REQ"

### ISSUE THREAD

**Issue by robinsowell** [ExpressionEngine/ExpressionEngine#4461]
Testing some pagination concerns- this url https://75gen:8890/about/page/P'qaAYqi%3C'%22%3ENMtADa/

Fatal error: Uncaught Error: Undefined constant "REQ" in /Users/robinsowell/Sites/75gen/system/ee/legacy/core/Exceptions.php:144 

Stack trace: #0 /Users/robinsowell/Sites/75gen/system/ee/ExpressionEngine/Boot/boot.common.php(346): EE_Exceptions->show_error('Error', 'The URI you sub...', 'error_general', 400) 

#1 /Users/robinsowell/Sites/75gen/system/ee/legacy/core/URI.php(275): show_error('The URI you sub...', 400) 
#2 /Users/robinsowell/Sites/75gen/system/ee/legacy/core/URI.php(220): EE_URI->_filter_uri('P'qaAYqi<'">NMt...') 
#3 /Users/robinsowell/Sites/75gen/system/ee/legacy/core/Router.php(105): EE_URI->_explode_segments() 
#4 /Users/robinsowell/Sites/75gen/system/ee/ExpressionEngine/Legacy/App.php(61): EE_Router->_set_routing() 
#5 /Users/robinsowell/Sites/75gen/system/ee/ExpressionEngine/Core/Core.php(85): ExpressionEngine\Legacy\App->overrideRouting(Array)
#6 /Users/robinsowell/Sites/75gen/system/ee/ExpressionEngine/Boot/boot.php(131): ExpressionEngine\Core\Core->overrideRouting(Array) 
#7 /Users/robinsowell/Sites/75gen/index.php(164): require_once('/Users/robinsow...') 
#8 {main} thrown in /Users/robinsowell/Sites/75gen/system/ee/legacy/core/Exceptions.php on line 144

**Comment by intoeetive** [comment]
@robinsowell I'm not getting the error with my install, just the blank page. Also nothing in error logs. But I don't have my index.php removed
